### ISSUE TITLE
Does not make use of `from_data_table` for the FASTA input

### ISSUE THREAD

**Issue by yhoogstrate** [Yating-L/ucsc_blat#1]
Example is given in:
https://github.com/galaxyproject/tools-iuc/blob/master/tool_collections/vcflib/vcfcheck/vcfcheck.xml#L26

**Comment by Yating-L** [comment]
Thank you for pointing it out! Currently the tool is developed as part of our sub-workflow of [G-OnRamp project](http://gonramp.wustl.edu). We may extend the tool to support full functionality as needed. Actually, I am considering to make use of "from_data_table". But it requires users to configure loc files and data-table themselves. Or they can use data managers tool to do it automatically but I found a problem of data managers tool https://biostar.usegalaxy.org/p/22918/
![blat_alignment](https://cloud.githubusercontent.com/assets/8609589/25826932/73f9f0ee-340e-11e7-9b9a-1020d4354986.png)

**Comment by yhoogstrate** [comment]
*But it requires users to configure loc files and data-table themselves.*
We usually make this optional by making a dropdown to either select a fasta from history or from the loc file / data_table, so users can benefit from both 😄 . Data managers for FASTA do already exist so you don't need to worry about this I suppose?

edit: once this tool works nicely, would you mind giving administrative permissions to IUC and add submit this tool to IUC with a pull request (https://github.com/galaxyproject/tools-iuc) so we may assist in further maintainance? I like blat and the wrapper 👍

**Comment by Yating-L** [comment]
I will add options of "select a fasta from history or from the loc file / data_table" to the wrapper and then submit a pull request to IUC.

**Comment by Yating-L** [comment]
Add from_data_table and from history options to import reference genome (https://github.com/Yating-L/ucsc_blat/commit/8860b60c42ac23449ba327bbe96d2ac667770268)
